### ISSUE TITLE
Pvalue doesn’t seem to match between the endpoints

### ISSUE THREAD

**Issue by msmanoj** [eQTL-Catalogue/eQTL-SumStats#24]
Pvalue is slightly different when comparing the value for rs2104375 between the current (use the link below and search for rs2104375) and new endpoint. Could you please check if this is expected?

Ensembl REST endpoint:
http://rest.ensembl.org/eqtl/variant_name/homo_sapiens/rs116930996?content-type=application/json;statistic=p-value

New Endpoint URL:
https://www.ebi.ac.uk/eqtl/api/associations/rs2104375?gene_id=ENSG00000139618&qtl_group=Whole_Blood

**Comment by jdhayhurst** [comment]
Hi Manoj,
The cohort and analysis and perhaps even the reference genome are different between GTEx v6 (Ensembl REST endpoint) and GTEx V8 (new endpoint) so we would expect to see differences in the values. The trend seen for both v6 and v8 should be similar but the absolute values will be different. So this difference that you've identified is acceptable.

**Comment by msmanoj** [comment]
Hi @jdhayhurst - Thanks for checking it and confirming. I guess this is no longer an issue.
