### ISSUE TITLE
Model the eqTL data in Mongo db for efficient loading and retrieval

### ISSUE THREAD

**Issue by sprintell** [eQTL-Catalogue/eQTL-SumStats#87]

**Comment by karatugo** [comment]
## Description

We need to design and implement an efficient data model for storing eQTL (expression Quantitative Trait Loci) data in MongoDB. The goal is to ensure that the data can be loaded quickly and retrieved efficiently to support API queries and downstream analyses. The data model should handle large datasets, optimize for query performance, and accommodate the specific structure of eQTL data.

**Comment by karatugo** [comment]
Moved to https://github.com/EBISPOT/eqtl-sumstats-service/issues/4
