### ISSUE TITLE
Develop a new data ingest / ETL pipeline for indexing eQTL data into the new mongo database.

### ISSUE THREAD

**Issue by sprintell** [eQTL-Catalogue/eQTL-SumStats#88]

**Comment by karatugo** [comment]
## Issue Description

We need to develop a robust and scalable data ingest/ETL (Extract, Transform, Load) pipeline to facilitate the reading of eQTL (expression Quantitative Trait Loci) data from FTP sources, indexing it into a MongoDB database, and serving it via an API. This pipeline will ensure efficient data extraction, transformation, and retrieval to support downstream analysis and querying through a web service.

**Comment by karatugo** [comment]
Moved to https://github.com/EBISPOT/eqtl-sumstats-service/issues/3
