### ISSUE TITLE
Redesigning the eQTL search API to utilize the new mongodb database

### ISSUE THREAD

**Issue by sprintell** [eQTL-Catalogue/eQTL-SumStats#89]

**Comment by karatugo** [comment]
## Description

We need to redesign the eQTL search API to integrate with the newly implemented MongoDB database. This involves updating the API endpoints to leverage the new data model and indexing strategies in MongoDB, ensuring efficient and scalable query performance. The redesigned API should support existing search functionalities and potentially add new features based on the enhanced capabilities of the MongoDB database.

**Comment by karatugo** [comment]
Moved to https://github.com/EBISPOT/eqtl-sumstats-service/issues/5
